configserver:
  name: JHipster Registry config server
  status: Connected to the JHipster Registry config server!
jhipster:
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
eureka:
    instance:
        prefer-ip-address: false
        nonSecurePort: 80
        appname: feedServices
        hostname: staging-feed.ap-southeast-1.elasticbeanstalk.com
spring:
    data:
        elasticsearch:
            cluster-name:search-staging-elk-xz63rprmcvpbm74hdf3nwlo534.ap-southeast-1.es.amazonaws.com
            cluster-nodes:
