configserver:
  name: JHipster Registry config server
  status: Connected to the JHipster Registry config server!
eureka:
    instance:
        prefer-ip-address: false
        nonSecurePort: 80
        appname: messageServices
        hostname: staging-message.ap-southeast-1.elasticbeanstalk.com
beecow:
    debugMode: true
    messageServices:
        firebase:
            private-key-file-path: classpath:config/firebase-admin-staging.json
            url: https://beecow-staging.firebaseio.com
            rootPath:
            userNode: Users
            roomNode: Rooms
            timeout: 30
            timeoutUnit: SECONDS
spring:
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data
