configserver:
  name: JHipster Registry config server
  status: Connected to the JHipster Registry config server!
eureka:
    instance:
        prefer-ip-address: false
        nonSecurePort: 80
        appname: notifyServices
        hostname: staging-notify.ap-southeast-1.elasticbeanstalk.com
spring:
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data
